import type { TranslationDictionary } from '../types/i18n'

const en: TranslationDictionary = {
  'nav.home': 'Home', 'nav.shop': 'Shop', 'nav.categories': 'Categories', 'nav.about': 'About Us', 'nav.account': 'Account', 'nav.logout': 'Log out', 'nav.openMenu': 'Open menu', 'nav.closeMenu': 'Close menu', 'nav.language': 'العربية',
  'login.eyebrow': 'Your ritual awaits', 'login.title': 'Welcome back to Veloura', 'login.subtitle': 'Sign in to continue your skincare journey.', 'login.email': 'Email address', 'login.password': 'Password', 'login.remember': 'Remember me', 'login.forgot': 'Forgot password?', 'login.signIn': 'Sign in', 'login.signingIn': 'Signing in...', 'login.newToVeloura': 'New to Veloura?', 'login.createAccount': 'Create an account', 'login.invalidEmail': 'Please enter a valid email address.', 'login.requiredPassword': 'Please enter your password.', 'login.success': 'Signed in successfully.',
  'login.heroEyebrow': 'The Veloura ritual', 'login.heroTitle': 'Your skin deserves a little more love.', 'login.heroText': 'Discover thoughtful skincare and build a healthy, glowing routine that feels entirely yours.', 'login.quote': 'Small rituals, lasting radiance.', 'login.quoteCaption': 'Clean beauty, considered.', 'login.emailPlaceholder': 'you@example.com', 'login.passwordPlaceholder': 'Enter your password', 'login.showPassword': 'Show', 'login.hidePassword': 'Hide', 'login.heroLabel': 'Veloura skincare introduction', 'login.forgotError': 'Login failed. Please try again.',
  'register.title': 'Welcome to Veloura', 'register.subtitle': 'Create your account and discover a gentler way to care for your skin.', 'register.fullName': 'Full name', 'register.createAccount': 'Create account', 'register.creatingAccount': 'Creating account...', 'register.alreadyMember': 'Already part of Veloura?', 'register.login': 'Log in', 'register.heroEyebrow': 'A softer approach to beauty', 'register.heroTitle': 'Begin your glow ritual.', 'register.heroText': 'Meet carefully chosen essentials for skin that feels nourished, balanced, and beautifully cared for.', 'register.quote': 'Your everyday care, made beautiful.', 'register.passwordPlaceholder': 'At least 8 characters', 'register.confirmPassword': 'Confirm password', 'register.confirmPlaceholder': 'Repeat password', 'register.passwordLength': 'Password must be at least 8 characters.', 'register.passwordMismatch': 'Passwords do not match.', 'register.invalidEmail': 'Please enter a valid email address.', 'register.success': 'Account created successfully. You can log in now.', 'auth.showPassword': 'Show password', 'auth.hidePassword': 'Hide password',
  'home.eyebrow': 'Thoughtful care, beautifully chosen', 'home.heroTitle': 'Your Skin, Your Ritual.', 'home.heroText': 'Discover carefully selected skincare essentials for a healthier, more radiant-looking you.', 'home.shopNow': 'Shop Now', 'home.explore': 'Explore Collection', 'home.curated': 'Curated formulas', 'home.mindful': 'Mindful rituals', 'home.edit': 'The edit', 'home.radiance': 'Everyday radiance', 'home.shopEyebrow': 'Shop the ritual', 'home.shopTitle': 'Simple steps to softer skin.', 'home.viewProducts': 'View all products', 'home.cleanse': 'Cleanse gently', 'home.hydrate': 'Hydrate deeply', 'home.protect': 'Protect daily', 'home.aboutEyebrow': 'Our point of view', 'home.aboutTitle': 'Beauty begins with how you care for yourself.', 'home.aboutText': 'Veloura is a considered collection of skincare essentials for the rituals that make everyday life feel a little more intentional. We believe in fewer, better products and formulas that fit beautifully into your real routine.', 'home.discover': 'Discover Veloura', 'footer.description': 'Thoughtful skincare for softer rituals and naturally radiant days.', 'footer.quickLinks': 'Quick links', 'footer.customerCare': 'Customer care', 'footer.contact': 'Contact', 'footer.shipping': 'Shipping', 'footer.returns': 'Returns', 'footer.faq': 'FAQ', 'footer.privacy': 'Privacy Policy', 'footer.stay': 'Stay in the ritual', 'footer.stayText': 'Notes on skin, self-care, and new Veloura arrivals.', 'footer.email': 'Your email address', 'footer.subscribe': 'Subscribe', 'footer.subscribed': "You're on the list. Welcome to the ritual.", 'footer.rights': 'All rights reserved.',
  'admin.workspace': 'Workspace', 'admin.dashboard': 'Dashboard', 'admin.products': 'Products', 'admin.categories': 'Categories', 'admin.orders': 'Orders', 'admin.customers': 'Customers', 'admin.settings': 'Settings', 'admin.logout': 'Log out', 'admin.storeOwner': 'Store owner', 'admin.overview': 'Overview / Dashboard', 'admin.search': 'Search anything...', 'admin.notifications': 'Notifications', 'admin.sales': 'Sales overview', 'admin.topProducts': 'Top products', 'admin.recentOrders': 'Recent orders', 'admin.viewAll': 'View all', 'admin.viewAllOrders': 'View all orders', 'admin.view': 'View', 'admin.status': 'Status', 'admin.date': 'Date', 'admin.total': 'Total', 'admin.customer': 'Customer', 'admin.orderId': 'Order ID', 'admin.action': 'Action', 'admin.today': 'Today', 'admin.thisWeek': 'This Week', 'admin.thisMonth': 'This Month', 'admin.thisYear': 'This Year', 'admin.fromLastMonth': 'from last month', 'admin.goodMorning': 'Good morning, Admin 👋', 'admin.todaySubtitle': "Here's what's happening with your store today.", 'admin.viewStore': 'View store', 'admin.totalSales': 'Total sales', 'admin.totalOrders': 'Total orders', 'admin.totalProducts': 'Total products', 'admin.totalCustomers': 'Total customers',
  'admin.manageProducts': 'Curate the essentials that make up the Veloura ritual.', 'admin.manageCategories': 'Shape the collections behind every Veloura ritual.', 'admin.manageOrders': 'Manage and review every order from your store.', 'admin.manageCustomers': 'Keep every customer conversation close to the Veloura ritual.', 'admin.catalog': 'Product catalog', 'admin.categoryCollection': 'Category collection', 'admin.contactMessages': 'Contact messages', 'admin.allOrders': 'All orders', 'admin.searchProducts': 'Search products...', 'admin.searchCategories': 'Search categories...', 'admin.searchMessages': 'Search messages...', 'admin.refresh': 'Refresh', 'admin.addProduct': 'Add product', 'admin.addCategory': 'Add category', 'admin.allStatus': 'All status', 'admin.allMessages': 'All messages', 'admin.noProducts': 'No products found', 'admin.noCategories': 'No categories found', 'admin.noMessages': 'No messages found',
}

export default en