<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>6b258f0d-5861-40fb-8eb5-686ad425990c</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="13.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.20" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.20">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />

		<PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />

		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="9.0.6" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Veloura.Application\Veloura.Application.csproj" />
		<ProjectReference Include="..\Veloura.Infrastructure\Veloura.Infrastructure.csproj" />
	</ItemGroup>

</Project>