<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="14.2.0" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.20">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />

		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Veloura.Application\Veloura.Application.csproj" />
		<ProjectReference Include="..\Veloura.Infrastructure\Veloura.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Controllers\" />
	</ItemGroup>

</Project>